print("*****Öğrenci Kaydı*****\n\n")
ad = input("Öğrencinin Adı: ")
soyad= input("Öğrencinin Soyadı: ")
bolum = input("Öğrencinin Bölümü: ")
no = input("Öğrencinin Okul Numarası: ")
print("\n")
print("Bilgiler Kaydediliyor...\n")
print("Adı: ", ad)
print("Soyadı: ",soyad)
print ("Bolum: ",bolum)
print("Okul Numarası: ",no)
print("\n\n")
print("Öğrencinin Bilgileri Kaydedildi.\n")
print("Teşekkürler..")